AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to create a Lambda function API gateway and Dynamodb.

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9

Resources:

  # DynamoDB Table
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RequestsLog
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Function
  GeneratePresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: ./src  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyDynamoDBTable
        - S3CrudPolicy:
            BucketName:   # Replace with your S3 bucket name
            
    # Permission for API Gateway to invoke the Lambda function
  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GeneratePresignedUrlFunction.Arn
      Principal: apigateway.amazonaws.com

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Presigned URL API"
          version: "1.0"
        paths:
          /generatePresignedUrl:
            post:
              summary: "Generate a presigned URL"
              parameters:
                - name: id
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                      id:
                        type: string
              responses:
                '200':
                  description: "Successful response"
                  schema:
                    type: object
                    properties:
                      url:
                        type: string
              x-amazon-apigateway-integration:
                uri: !Sub
                  arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GeneratePresignedUrlFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for generating presigned URLs"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/generatePresignedUrl"
